# Generated by Django 5.2.9 on 2025-12-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclass',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Maximum number of students', null=True),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g., '8 weeks', '2 months'", max_length=100),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherclass',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
